### ISSUE TITLE
NoMethodError: undefined method `gen_if_not_exists' 

### ISSUE THREAD

**Issue by HatemMS2012** [EOL/eol#109]
Hi,

while I am executing ```rake eol:db:rebuild``` I get the following error message: 

```
NoMethodError: undefined method `gen_if_not_exists' for #<Class:0x6759cc0>
scenarios/foundation.rb:20:in `block in <top (required)>'
scenarios/foundation.rb:19:in `<top (required)>'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol_scenarios/eol_scenario.rb:210:in `load'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol_scenarios/eol_scenario.rb:210:in `block in load'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol_scenarios/eol_scenario.rb:200:in `each'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol_scenarios/eol_scenario.rb:200:in `load'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol/scenario_loader.rb:71:in `load_and_cache'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol/scenario_loader.rb:30:in `load_with_caching'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol/scenario_loader.rb:19:in `load_with_caching'
c:/Users/localadmin/workspace/eolOLdApp/lib/scenario_helpers.rb:17:in `load_scenario_with_caching'
c:/Users/localadmin/workspace/eolOLdApp/lib/scenario_helpers.rb:11:in `load_foundation_cache'
scenarios/bootstrap.rb:29:in `<top (required)>'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol_scenarios/eol_scenario.rb:210:in `load'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol_scenarios/eol_scenario.rb:210:in `block in load'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol_scenarios/eol_scenario.rb:200:in `each'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol_scenarios/eol_scenario.rb:200:in `load'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol/scenario_loader.rb:71:in `load_and_cache'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol/scenario_loader.rb:30:in `load_with_caching'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol/scenario_loader.rb:19:in `load_with_caching'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol_scenarios/tasks.rb:33:in `block (3 levels) in <top (required)>'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol_scenarios/tasks.rb:32:in `each'
c:/Users/localadmin/workspace/eolOLdApp/lib/eol_scenarios/tasks.rb:32:in `block (2 levels) in <top (required)>'
Tasks: TOP => scenarios:load
```
Would it be possible to help me with this issue?

Thank you!!

**Comment by JRice** [comment]
Sorry, I don't believe we have time to look into this right now.

That method is defined in spec/eol_factory_girl.rb, so apparently, whatever process you are using to run that rake task is not loading this file. I would try explicitly loading it somewhere, if you must, but it might be more useful to track down where it's supposed to have been loaded, as there are likely other includes that are missing.

Good luck; sorry!

**Comment by HatemMS2012** [comment]
Thank you very much for this hint. I think it will help me to advance with the installation.
Cheers,
